# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            plotly
tagline:          'An R wrapper to the Plot.ly API'
description:      'Interactive graphics'

author:
  name:           'jane doe'
  url:            https://twitter.com/janedoe

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/ropensci/plotly
